
services:
  gemini-claude-proxy:
    build:
      context: .
      dockerfile: Dockerfile
      # 适应慢速网络环境
      args:
        - HTTP_PROXY=${HTTP_PROXY:-}
        - HTTPS_PROXY=${HTTPS_PROXY:-}
    container_name: gemini-claude-proxy
    network_mode: host
    volumes:
      # 持久化配置数据
      - ./data:/app/data
    restart: unless-stopped
    # 健康检查配置
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# 快速开始：
# 必须设置超长超时时间（重要！）
# export DOCKER_BUILDKIT=1
# export COMPOSE_HTTP_TIMEOUT=600000
# export DOCKER_CLIENT_TIMEOUT=600000
# 
# 然后运行：
# docker-compose up -d
# 
# 访问：http://localhost:9000
# 默认密码：admin123

# 慢速网络环境：
# 1. 设置上述环境变量（必须！）
# 2. 可选：使用代理
#    export HTTP_PROXY=http://your-proxy:port
#    export HTTPS_PROXY=http://your-proxy:port
# 3. 可选：使用国内镜像（编辑 Dockerfile 取消注释）
