services:
  gemini-claude-proxy:
    build:
      context: .
      dockerfile: Dockerfile
      # 适应慢速网络环境
      args:
        - HTTP_PROXY=${HTTP_PROXY:-}
        - HTTPS_PROXY=${HTTPS_PROXY:-}
    container_name: gemini-claude-proxy
    network_mode: host
    volumes:
      # 持久化配置数据
      - ./data:/app/data
    environment:
      # 请求大小限制（支持大项目和大文件）
      # 默认 200mb，可根据需要调整
      - REQUEST_SIZE_LIMIT=${REQUEST_SIZE_LIMIT:-200mb}
    restart: unless-stopped
    # 健康检查配置
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# 快速开始：
# 
# 慢速网络解决方案：
# 
# 1. 配置 Docker 镜像加速（必须！）
#    sudo mkdir -p /etc/docker
#    sudo tee /etc/docker/daemon.json <<EOF
#    {
#      "registry-mirrors": [
#        "https://docker.mirrors.ustc.edu.cn",
#        "https://hub-mirror.c.163.com"
#      ]
#    }
#    EOF
#    sudo systemctl restart docker
#
# 2. 先拉取基础镜像
#    docker pull node:20-alpine
#
# 3. 编辑 Dockerfile，取消注释第 10 行和第 25 行（使用国内源）
#
# 4. 构建并启动
#    docker compose build --no-cache
#    docker compose up -d
# 
# 访问：http://localhost:9000
# 默认密码：admin123
