
services:
  gemini-claude-proxy:
    build: .
    container_name: gemini-claude-proxy
    ports:
      - "9000:9000"
    volumes:
      # 持久化配置数据
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# 快速开始：
# 1. 运行：docker-compose up -d
# 2. 访问：http://localhost:9000
# 3. 使用默认密码 admin123 登录
# 4. 在配置页面设置你的 Gemini API Key 和其他参数
